#  工程文件结构

info:
  project_name: "xxxxxxx"  #工程名
  project_path: "xxxxxxxx" #工程保存的路径

#基本参数
#使用的中央经线



#资源管理

#站点信息

stations: 
  - id: 1
    name: xxxxx
    notes: "xxxxxxxxxx"   #站点备注
    type: "static"   #站点类型  静态/动态
    coord:
      - type: "set"
        coord: [100.00,100.00,100.00]
      - type: "spp"
        ecef_x: [100.00,100.00,100.00]
      - type: "adjust"
        ecef_x: [100.00,100.00,100.00]  
      - type: "baseline"
        ecef_x: [100.00,100.00,100.00]  
  - id: 2
    name: xxxxx
    notes: "xxxxxxxxxx"   #站点备注
    type: "dynamic"   #站点类型  静态/动态
    coord:           #动态站点没有坐标
      - type: "default"
        coord: [0.00,0.00,0.00]

obsfile:
  - id: 1
    file_name: xx
    file_path: xx
    station_name: "xxxxxxx"
    file_start_time: 10000.0
    file_end_time: 20000.0
    file_time_span: 863399
    measurement_method: 
    measurement_ant_height:
    ant_height_corrent:
    ant_phase_height:
    ant_pedestal_height:
    ant_manufacturer:
    ant_type:
    ant_sn:
    receiver_sn:
    receiver_type:
    receiver_version:
    rinex_measurement_method:
    rinex_ant_height:
    rinex_ant_type:
    rinex_manufacturer:


baseline:
  - id: 1
    baseline_id:
    baseline_type:
    start_station:
    end_station:
    start_file:
    end_file:
    solution_type:
    utilization_percentage:
    sync_seconds:
    solution_ratio:
    solution_rms:
    solution_check:
    solution_dx:
    solution_dy:
    solution_dz:
    solution_stdx:
    solution_stdy:
    solution_stdz:
    solution_horizontal_distance:
    solution_slope_distance:
    solution_elevation_difference:
    solution_forward_angle:
    solution_ellipsoidal_distance:
    solution_geodetic_height:
    solution_RDOP:
    solution_PDOP:
    solution_HDOP:
    solution_VDOP:
    baseline_enuse:



